jersey/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main, add_jersey, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, edit_jersey, delete_jersey, add_jersey_ajax, create_jersey_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('add-jersey/', add_jersey, name='add_jersey'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('logout/', logout_user, name='logout'),
    path('login/', login_user, name='login'),
    path('edit-jersey/<uuid:id>/', edit_jersey, name='edit_jersey'),
    path('delete-jersey/<uuid:id>/', delete_jersey, name='delete_jersey'),
    path('add-jersey-ajax', add_jersey_ajax, name='add_jersey_ajax'),
    path('create-flutter/', create_jersey_flutter, name='create_jersey_flutter'),
 ]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block meta %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% endblock meta %}
        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/global.css' %}"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Source+Code+Pro:ital,wght@0,200..900;1,200..900&family=Urbanist:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
        
        <title>{% block title %}JerseyKu Store{% endblock %}</title>
    </head>
    <body>
        {% block content %}
        {% endblock %}
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        {% block additional_js %}{% endblock %}
    </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light fixed-top">
  <div class="container">
    <a class="navbar-brand" href="#">JERSEYKU .</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#carouselExampleIndicators">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#catalogue-section">Catalogue</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Welcome, {{ user.username }}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link logout-link" href="{% url 'main:logout' %}">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>


<style>
body {
  font-family: 'Urbanist', sans-serif;
}


.navbar {
    background: linear-gradient(
        to bottom,
        #d3b89c 5%, 
        rgb(63, 82, 83) 5% 95%, 
        #d3b89c 95% 100% 
    );
    font-family: 'Urbanist', sans-serif; /* Applying Verdana to navbar */
}

.nav-link{
    color: #fff;
    font-family: 'Urbanist', sans-serif;
}

.navbar-brand {
  font-family: 'Urbanist', sans-serif;
  font-weight: bold;
}

.navbar-brand:hover {
  color: rgb(233, 229, 224);
}

.navbar-light .navbar-nav .active > .nav-link, .navbar-light .navbar-nav .nav-link.active, .navbar-light .navbar-nav .nav-link.show, .navbar-light .navbar-nav .show > .nav-link {
  color: #fff;
}

.navbar-brand {
  color: #fff;
}

.navbar-light .navbar-nav {
  color: #e6e6e6;
}

.navbar-toggler {
  background: #e6e6e6;
}

.navbar-nav {
    padding-right: 0; /* Remove padding if any */
    margin-right: 0; /* Adjust margin to ensure alignment */
}


.nav-link {
  padding: .2rem 1rem;
}

.nav-link.active,.nav-link:focus{
  color: #fff;
}

.navbar-toggler {
  padding: 1px 5px;
  font-size: 18px;
  line-height: 0.3;
}

.navbar-light .navbar-nav .nav-link:focus, .navbar-light .navbar-nav .nav-link:hover {
  color: #fff;
}

.logout-link {
    display: inline-block; 
    text-align: center;
    background-color: #8b1a1a;
    color: white;
    font-weight: bold;
    padding: 5px 8px;
    border-radius: 0.375rem;
    transition: background-color 0.3s;
    margin-top: 2px;
    margin-bottom: 2px;
}

.logout-link:hover {
    background-color: rgb(82, 12, 12);
}

@media (max-width: 992px) {
    .nav-item {
        width: 100%; 
    }

    .logout-link {
        display: block; 
        width: 100%; 
        padding: 8px 16px; 
      }
}

.nav-item {
    align-items: center; /* Center align items vertically */
    display: flex; /* Use flexbox for alignment */
    margin-right: 20px;
    text-transform: uppercase;
    font-size: 12px;
}



.link-area
{
  position:fixed;
  bottom:20px;
  left:20px;  
  padding:15px;
  border-radius:40px;
}
.link-area a
{
  text-decoration:none;
  color:#fff;
}

.navbar-collapse {
    justify-content: flex-end; /* Aligns nav items to the right */
}

</style>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  document.addEventListener("DOMContentLoaded", function() {
      // Select all links within the navbar
      document.querySelectorAll('.navbar-nav>li>a').forEach(function(element) {
          element.addEventListener('click', function () {
              // Check if the menu is open
              const navbarToggler = document.querySelector('.navbar-toggler');
              const bsCollapse = new bootstrap.Collapse(document.getElementById('navbarSupportedContent'), {
                  toggle: false
              });
              if(!navbarToggler.classList.contains('collapsed')) {
                  bsCollapse.hide();
              }
          });
      });
  });
  </script>